/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package navigator;

import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import navigator.basicobjects.NavObject;

/**
 *
 * @author abdel
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        int[] types_visibles=new int[NavObject.types.length];
        for (int i=0; i< NavObject.types.length;i++) {
            types_visibles[i]=i;
        }
        liste_types_visibles.setSelectedIndices(types_visibles);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        btn_charger_image = new javax.swing.JButton();
        label_echel = new javax.swing.JLabel();
        text_echel = new javax.swing.JTextField();
        combobox_type_objet = new javax.swing.JComboBox<>();
        label_ajouter = new javax.swing.JLabel();
        text_size = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_objets = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        liste_types_visibles = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneauNavigation2 = new navigator.PaneauNavigation(liste_types_visibles);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        btn_charger_image.setText("Charger Image");
        btn_charger_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_charger_imageMouseClicked(evt);
            }
        });

        label_echel.setLabelFor(text_echel);
        label_echel.setText("Echel:");
        label_echel.setNextFocusableComponent(text_echel);

        text_echel.setText("1");
        text_echel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                text_echelPropertyChange(evt);
            }
        });

        combobox_type_objet.setModel(new javax.swing.DefaultComboBoxModel<>(NavObject.types));
        combobox_type_objet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_type_objetActionPerformed(evt);
            }
        });

        label_ajouter.setText("Ajouter:");

        text_size.setText("1");
        text_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_sizeActionPerformed(evt);
            }
        });

        jLabel1.setText("Taille:");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_size, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_charger_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(leftPanelLayout.createSequentialGroup()
                            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_echel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combobox_type_objet, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_echel)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btn_charger_image)
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_echel)
                    .addComponent(text_echel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_type_objet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ajouter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        jSplitPane2.setDividerLocation(600);
        jSplitPane2.setResizeWeight(1.0);

        table_objets.setModel(new ObjetsTableModel(paneauNavigation2));
        jScrollPane2.setViewportView(table_objets);

        liste_types_visibles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = NavObject.types;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        liste_types_visibles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                liste_types_visiblesValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(liste_types_visibles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 154, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel3);

        paneauNavigation2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paneauNavigation2MouseDragged(evt);
            }
        });
        paneauNavigation2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneauNavigation2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneauNavigation2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paneauNavigation2MouseReleased(evt);
            }
        });
        paneauNavigation2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                paneauNavigation2ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout paneauNavigation2Layout = new javax.swing.GroupLayout(paneauNavigation2);
        paneauNavigation2.setLayout(paneauNavigation2Layout);
        paneauNavigation2Layout.setHorizontalGroup(
            paneauNavigation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        paneauNavigation2Layout.setVerticalGroup(
            paneauNavigation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(paneauNavigation2);

        jSplitPane2.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_type_objetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_type_objetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_type_objetActionPerformed

    private void text_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_sizeActionPerformed

    private void paneauNavigation2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneauNavigation2MouseClicked
        // TODO add your handling code here:
        if(evt.getButton()==MouseEvent.BUTTON1){
            if(evt.getClickCount()==2){
                
                System.out.println("double click");
                NavObject newObjet=new NavObject(combobox_type_objet.getSelectedIndex(), "", "", null, "", evt.getX(), evt.getY(), 30+Integer.parseInt(text_size.getText()), true);
                for (NavObject next : paneauNavigation2.getObjetsNavigation()) {
                    if(next.equals(newObjet))return;   
                }
                //TODO: Dialog
                NouveauDialog nd =new NouveauDialog(this, true);
                nd.setTitle("Nouveau: "+NavObject.types[combobox_type_objet.getSelectedIndex()]);
                nd.setVisible(true);
                if(nd.isValide()){
                    newObjet.setTitre(nd.getTitre());
                    newObjet.setAdresse(nd.getAdresse());
                    newObjet.setImage(nd.getImage());
                    newObjet.setDescription(nd.getDescription());
                    paneauNavigation2.getObjetsNavigation().add(newObjet);
                    ((ObjetsTableModel)table_objets.getModel()).fireTableDataChanged();
                }  
            }else if(evt.getClickCount()==1){ 
                for (NavObject next : paneauNavigation2.getObjetsNavigation()) {
                    if(next.apartient(evt.getX(),evt.getY()))selectionne=next;  
                }
                //TODO: affichage des informations sur l'objet
                
                selectionne=null;
            } 
        }else if(evt.getButton()==MouseEvent.BUTTON3){
            for (NavObject next : paneauNavigation2.getObjetsNavigation()) {
                if(next.apartient(evt.getX(),evt.getY()))selectionne=next;  
            }
            paneauNavigation2.getObjetsNavigation().remove(selectionne);
        }
        
        paneauNavigation2.repaint();
    }//GEN-LAST:event_paneauNavigation2MouseClicked

    private void paneauNavigation2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paneauNavigation2ComponentResized
        // TODO add your handling code here:
        paneauNavigation2.setPreferredSize(paneauNavigation2.getSize());
        jScrollPane1.validate();
    }//GEN-LAST:event_paneauNavigation2ComponentResized

    private NavObject selectionne =null;
    private void paneauNavigation2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneauNavigation2MousePressed
        // TODO add your handling code here:
        if(evt.getButton()==MouseEvent.BUTTON1){
            for (NavObject next : paneauNavigation2.getObjetsNavigation()) {
                if(next.apartient(evt.getX(),evt.getY()))selectionne=next;
            }
        }
    }//GEN-LAST:event_paneauNavigation2MousePressed

    private void paneauNavigation2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneauNavigation2MouseReleased
        // TODO add your handling code here:
        if(evt.getButton()==MouseEvent.BUTTON1){
            selectionne =null;
        }
    }//GEN-LAST:event_paneauNavigation2MouseReleased

    private void paneauNavigation2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneauNavigation2MouseDragged
        // TODO add your handling code here:
        int type=combobox_type_objet.getSelectedIndex();
        if(type<0 || type>NavObject.types.length-1){
            
        }else{
            if(selectionne!=null){
                selectionne.setX(evt.getX());
                selectionne.setY(evt.getY());
            }
        }
        paneauNavigation2.repaint();
    }//GEN-LAST:event_paneauNavigation2MouseDragged

    private void btn_charger_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_charger_imageMouseClicked
        // TODO add your handling code here:
        JFileChooser file_chooser = new JFileChooser();
        file_chooser.setFileFilter(new FileNameExtensionFilter("Images", new String[]{"jpg","png","gif","jpeg"}));
        file_chooser.showDialog(this, "Charger");
        ///////modifier verification
        
        if(file_chooser.getSelectedFile().exists()){ImageIcon icon = new ImageIcon(file_chooser.getSelectedFile().getAbsolutePath()); paneauNavigation2.setImage(icon.getImage()); jScrollPane1.repaint();}
        
    }//GEN-LAST:event_btn_charger_imageMouseClicked

    private void text_echelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_text_echelPropertyChange
        // TODO add your handling code here:
        int v=Integer.parseInt(text_echel.getText());
        paneauNavigation2.setScale(v);
    }//GEN-LAST:event_text_echelPropertyChange

    private void liste_types_visiblesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_liste_types_visiblesValueChanged
        // TODO add your handling code here:
        paneauNavigation2.getObjetsNavigation().forEach((next) -> {
            next.setVisibilite(false);
            for (int typeV : liste_types_visibles.getSelectedIndices()) {
                if(next.getType()==typeV){next.setVisibilite(true);break;}
            }
        });
        ((ObjetsTableModel)table_objets.getModel()).fireTableDataChanged();
        paneauNavigation2.repaint();
    }//GEN-LAST:event_liste_types_visiblesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
            //i propose to ...
      
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_charger_image;
    private javax.swing.JComboBox<String> combobox_type_objet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel label_ajouter;
    private javax.swing.JLabel label_echel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JList<String> liste_types_visibles;
    private navigator.PaneauNavigation paneauNavigation2;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable table_objets;
    private javax.swing.JTextField text_echel;
    private javax.swing.JTextField text_size;
    // End of variables declaration//GEN-END:variables
}
